name: Sync with Ubuntu

on:
  push:
    branches:
      - main   

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync with Ubuntu
        run: |
          ssh ${{ secrets.USERNAME }}@${{secrets.IP_HOST}} "cd /home/sites/onegaleon && git pull origin main"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
